apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: jayaanandborra
    provider: github
    repository: angular-jenkins-x
  name: jayaanandborra-angular-jenkins-x
spec:
  description: Imported application for jayaanandborra/angular-jenkins-x
  httpCloneURL: https://github.com/jayaanandborra/angular-jenkins-x.git
  org: jayaanandborra
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: angular-jenkins-x
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/jayaanandborra/angular-jenkins-x.git
